<?php
// $Id: $

function brendans_block_info() {
    $blocks['Weather'] = array(
        'info' => t('Weather Display for front page'),
    );

    return $blocks;
}

function brendans_block_configure($delta) {

    $form = array();

    switch($delta){
        case 'Weather':
            $form['zipForWeather'] = array(
                '#type' => 'textfield',
                '#title' => t('Zip Code for Weather'),
                '#size' => 6,
                '#description' => t('Enter Zip Code to be used for Weather'),
                '#default_value' => variable_get('zipForWeather', 23456),
            );
    }

    return $form;
}


/**
 * Implements hook_block_save().
 */
function brendans_block_save($delta = '', $edit = array()) {
    switch($delta) {
        case 'Weather':
            variable_set('zipForWeather', (int)$edit['zipForWeather']);
            break;
    }
    return;
}

function brendans_block_view($delta) {
    $block = array();

    switch($delta){
        case 'Weather':
            $block['subject'] = 'Weather Block';
            $block['content'] = theme('brendans_template');
            break;
    }

    return $block;
}

function brendans_theme($existing, $type, $theme, $path) {
    return array(
        'brendans_template' => array(
            'variables' => array('title' => "Weather Block", 'content' => brendans_weather_content()),
            'template' => 'brendans-template',
        ),
    );
}

function brendans_weather_content() {

    $zipToUse = variable_get('zipForWeather',23456);
    $result = file_get_contents('http://i.wxbug.net/REST/Direct/GetData.ashx?zip=' . $zipToUse .'&dt=l&dt=o&ic=1&dt=f&nf=3&api_key=2ncdmku9esspx8r653psbmfc');
    $data = json_decode($result);
    $sendToBlock = array("todayHigh" => $data->weather->ForecastData->forecastList[0]->high,
    "todayLow" => $data->weather->ForecastData->forecastList[0]->low,
    "todayDesc" => $data->weather->ForecastData->forecastList[0]->dayDesc,
    "todayIcon" => $data->weather->ForecastData->forecastList[0]->dayIcon,
    "tomorrowHigh" => $data->weather->ForecastData->forecastList[1]->high,
    "tomorrowLow" => $data->weather->ForecastData->forecastList[1]->low,
    "tomorrowDesc" => $data->weather->ForecastData->forecastList[1]->dayDesc,
    "tomorrowIcon" => $data->weather->ForecastData->forecastList[1]->dayIcon,
    "cityName" => $data->weather->LocationData->location->city,
    "stateName" => $data->weather->LocationData->location->state,
    "currentTemp" => $data->weather->ObsData->temperature,
    "currentCondCode" => $data->weather->ObsData->icon,
    "currentWeatherDesc" => $data->weather->ObsData->desc);

    return $sendToBlock;
}

