<?php
// $Id: $

function brendans_block_info() {
    $blocks['Weather'] = array(
        'info' => t('Weather Display for front page'),
    );

    return $blocks;
}

function brendans_block_view($delta) {
    $block = array();

    switch($delta){
        case 'Weather':
            $block['subject'] = 'Weather Block';
            $block['content'] = theme('brendans_template');
            break;
    }

    return $block;
}

function brendans_theme($existing, $type, $theme, $path) {
    return array(
        'brendans_template' => array(
            'variables' => array('title' => "Weather Block", 'content' => brendans_weather_content()),
            'template' => 'brendans-template',
        ),
    );
}

function brendans_weather_content() {

    $result = file_get_contents('http://i.wxbug.net/REST/Direct/GetData.ashx?zip=23454&dt=l&dt=o&ic=1&dt=f&nf=3&api_key=2ncdmku9esspx8r653psbmfc');
    $data = json_decode($result);
    $sendToBlock = array("todayHigh" => $data->weather->ForecastData->forecastList[0]->high,
    "todayLow" => $data->weather->ForecastData->forecastList[0]->low,
    "cityName" => $data->weather->LocationData->location->city,
    "stateName" => $data->weather->LocationData->location->state,
    "currentTemp" => $data->weather->ObsData->temperature,
    "currentCondCode" => $data->weather->ObsData->icon);


    return $sendToBlock;
}

